name: git-secrets

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source

      - name: Checkout OneLogin Actions
        uses: actions/checkout@v2
        with:
          repository: onelogin/.github-private
          token: ${{ secrets.IKE_BOT_PAT }}
          path: onelogin-actions

      - uses: ./onelogin-actions/security/actions/git-secrets-install/v1
      - uses: ./onelogin-actions/security/actions/git-secrets-scan/v1
